name:                Ki
version:             0.1.0.0
github:              "githubuser/ki"
license:             RPL
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ki#readme>

dependencies:
- base >= 4.7 && < 5
- path
- text
- path-io
- pureMD5
- bytestring
- microaeson
- sqlite-simple
- slugify
- containers
- protobuf
- libgit
- filepath
- HsYAML
- attoparsec
- replace-attoparsec
- uri-encode
- regex-tdfa
- regex-compat

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

c-sources: htidy.c
install-includes: htidy.h
include-dirs: /usr/include/tidy

executables:
  Ki-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  Ki-test:
    main:                Tests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
