name:                Ki
version:             0.1.0.0
github:              "githubuser/ki"
license:             RPL
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ki#readme>

custom-setup:
  dependencies:
  - base
  - Cabal
  - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

extra-source-files: proto/**/*.proto

dependencies:
- base >= 4.7 && < 5
- path
- text
- path-io
- pureMD5
- bytestring
- microaeson
- sqlite-simple
- slugify
- containers
- libgit
- filepath
- HsYAML
- attoparsec
- replace-attoparsec
- uri-encode
- regex-tdfa
- regex-compat
- pretty-simple
- terminal-progress-bar

library:
  dependencies:
  - base
  - proto-lens-runtime

  exposed-modules:
  - Proto.Notetypes
  - Proto.Notetypes_Fields
  - Proto.Collection
  - Proto.Collection_Fields
  - Proto.Generic
  - Proto.Generic_Fields

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

cc-options: -shared

executables:
  Ki-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - proto-lens
    # The following dependency works around a bug with Cabal-1.*.  It is not
    # needed with Cabal-2.0 or later (stack lts-10.0 or later).
    - proto-lens-runtime
    - Ki

tests:
  Ki-test:
    main:                Tests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
